name: dt_money
description: A refactored version of a previous app that I made, using the BLoC library.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.1

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # flutter gen-l10n
  phosphor_flutter: ^1.4.0
  shared_preferences: ^2.0.17
  stream_transform: ^2.1.0
  url_launcher: ^6.1.9

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1 # flutter packages pub run build_runner build
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
